name: Build and Push Angular Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Angular application
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Create Dockerfile if missing
      - name: Create Dockerfile if not exists
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Creating Dockerfile..."

            cat <<EOF > Dockerfile
            FROM nginx:alpine

            COPY dist /usr/share/nginx/html

            EXPOSE 80

            CMD ["nginx", "-g", "daemon off;"]
            EOF
          else
            echo "Dockerfile already exists."
          fi

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-app:latest .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
